sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  redis:
    password: ${REDIS_PASSWORD}
